# Train the letter recognizer and export it for the browser (js/letters-model.js).
import json, math, sys, time, base64
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from gen import CLASSES

torch.set_num_threads(4)
torch.manual_seed(0)
NC = len(CLASSES)


class Net(nn.Module):
    def __init__(self, c=(16, 32, 64, 96), fc=128):
        super().__init__()
        self.c1 = nn.Conv2d(1, c[0], 3, padding=1); self.b1 = nn.BatchNorm2d(c[0])
        self.c2 = nn.Conv2d(c[0], c[1], 3, padding=1); self.b2 = nn.BatchNorm2d(c[1])
        self.c3 = nn.Conv2d(c[1], c[2], 3, padding=1); self.b3 = nn.BatchNorm2d(c[2])
        self.c4 = nn.Conv2d(c[2], c[3], 3, padding=1); self.b4 = nn.BatchNorm2d(c[3])
        self.f1 = nn.Linear(c[3] * 16, fc)
        self.f2 = nn.Linear(fc, NC)
        self.drop = nn.Dropout(0.3)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.b1(self.c1(x))), 2)   # 16×16
        x = F.max_pool2d(F.relu(self.b2(self.c2(x))), 2)   # 8×8
        x = F.max_pool2d(F.relu(self.b3(self.c3(x))), 2)   # 4×4
        x = F.relu(self.b4(self.c4(x)))                    # 4×4
        x = self.drop(F.relu(self.f1(x.flatten(1))))
        return self.f2(x)


def load(fn):
    d = np.load(fn)
    return torch.from_numpy(d['X']), torch.from_numpy(d['y'].astype(np.int64))


def evaluate(net, X, y, bs=2048):
    net.eval(); correct = 0; top3 = 0
    with torch.no_grad():
        for i in range(0, len(X), bs):
            xb = X[i:i + bs].float().unsqueeze(1) / 255.0
            out = net(xb)
            t3 = out.topk(3, 1).indices
            correct += (t3[:, 0] == y[i:i + bs]).sum().item()
            top3 += (t3 == y[i:i + bs, None]).any(1).sum().item()
    return correct / len(X), top3 / len(X)


def export(net, fn):
    net.eval()
    layers = []

    def conv(c, b):
        s = b.weight / torch.sqrt(b.running_var + b.eps)
        W = c.weight * s[:, None, None, None]
        B = (c.bias - b.running_mean) * s + b.bias
        return W.detach().numpy(), B.detach().numpy()

    for c, b in [(net.c1, net.b1), (net.c2, net.b2), (net.c3, net.b3), (net.c4, net.b4)]:
        W, B = conv(c, b)
        layers.append(('conv', W, B))
    layers.append(('fc', net.f1.weight.detach().numpy(), net.f1.bias.detach().numpy()))
    layers.append(('fc', net.f2.weight.detach().numpy(), net.f2.bias.detach().numpy()))
    out = []
    for kind, W, B in layers:
        oc = W.shape[0]
        flat = W.reshape(oc, -1)
        scale = np.abs(flat).max(1) / 127.0
        scale[scale == 0] = 1
        q = np.clip(np.round(flat / scale[:, None]), -127, 127).astype(np.int8)
        out.append({
            'kind': kind, 'shape': list(W.shape),
            'w': base64.b64encode(q.tobytes()).decode(),
            'scale': base64.b64encode(scale.astype(np.float32).tobytes()).decode(),
            'bias': base64.b64encode(B.astype(np.float32).tobytes()).decode(),
        })
    model = {'classes': CLASSES, 'input': 32, 'box': 28, 'layers': out}
    js = ('/* SANSTYLE — letters-model.js (generated by tools/recognizer/train.py)\n'
          ' * The letter recognizer\'s weights: a small convolutional network trained on\n'
          ' * handwritten characters and ~700 fonts distorted to look like extracted\n'
          ' * graffiti. See js/recognize.js. */\n'
          '(function (g) { (g.ST || (g.ST = {})).lettersModel = ' + json.dumps(model, separators=(',', ':')) + '; })'
          "(typeof window !== 'undefined' ? window : (typeof self !== 'undefined' ? self : globalThis));\n")
    open(fn, 'w').write(js)
    return model


if __name__ == '__main__':
    epochs = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    import os
    def loads(names):
        parts = [load(n) for n in names if os.path.exists(n)]
        return torch.cat([p[0] for p in parts]), torch.cat([p[1] for p in parts])
    Xtr, ytr = loads(['train.npz', 'train2.npz']); Xva, yva = loads(['val.npz', 'val2.npz'])
    print('train', Xtr.shape, 'val', Xva.shape, flush=True)
    net = Net()
    print('params', sum(p.numel() for p in net.parameters()), flush=True)
    opt = torch.optim.AdamW(net.parameters(), lr=2e-3, weight_decay=1e-4)
    bs = 256
    steps = epochs * (len(Xtr) // bs)
    sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=3e-3, total_steps=steps, pct_start=0.15)
    lossf = nn.CrossEntropyLoss(label_smoothing=0.05)
    for ep in range(epochs):
        net.train(); t0 = time.time(); perm = torch.randperm(len(Xtr)); tot = 0
        for i in range(0, len(Xtr) - bs + 1, bs):
            idx = perm[i:i + bs]
            xb = Xtr[idx].float().unsqueeze(1) / 255.0
            loss = lossf(net(xb), ytr[idx])
            opt.zero_grad(); loss.backward(); opt.step(); sched.step()
            tot += loss.item()
        acc, a3 = evaluate(net, Xva, yva)
        print(f'epoch {ep + 1} loss {tot / (len(Xtr) // bs):.3f} val top1 {acc:.3f} top3 {a3:.3f} ({time.time() - t0:.0f}s)', flush=True)
        torch.save(net.state_dict(), 'net.pt')
    export(net, 'letters-model.js')
    # reference outputs for the JS port
    net.eval()
    with torch.no_grad():
        xb = Xva[:8].float().unsqueeze(1) / 255.0
        ref = torch.softmax(net(xb), 1).numpy()
    json.dump({'x': Xva[:8].numpy().reshape(8, -1).tolist(), 'p': ref.tolist()}, open('ref.json', 'w'))
    print('exported', flush=True)
